### ISSUE TITLE
Milestone 2 Individual Documents

### ISSUE THREAD

**Issue by DJ-CO** [annalieseschropp/checkers#80]
Remember to submit your individual evaluations for Milestone 2.

- [x] D.J.'s individual evaluation done
- [x] Annie's individual evaluation done
- [x] Sahibjeet's individual evaluation done
- [ ] Ian's individual evaluation done
